import { StyleSheet } from "react-native";
import { SCREEN_W, SCREEN_H } from "@/constants/onboarding/dimensions";
import { GOALS_LIST_ROW_GAP } from "@/constants/onboarding/goalsList";
import { JOURNEY_GRID_SIDE_PADDING, JOURNEY_GRID_VERTICAL_PADDING } from "@/constants/onboarding/journey";
import {
  ONBOARDING_STREAK_DAY_CELL_SIZE,
  ONBOARDING_STREAK_DAY_ROW_GAP,
} from "@/constants/onboarding/content";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  headerAbsolute: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 20,
  },
  headerImage: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 4,
  },
  backBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  backBtnSmall: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollFlex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  /** Goals step (screen 7): reserve space above fixed footer so list clears Continue + progress dots. */
  scrollContentGoalsStep: {
    paddingBottom: 140,
  },
  /** Dhikr frequency step (screen 8): extra air above Continue so the slider block is not compressed. */
  scrollContentFrequencyStep: {
    paddingBottom: 108,
  },
  /** First dhikr demo (screen 13): no Continue — content breathes above progress dots only. */
  scrollContentDhikrStep: {
    paddingBottom: 16,
  },
  /** Dhikr step: footer is progress dots only; balanced inset from home indicator. */
  footerDhikrProgressOnly: {
    paddingTop: 6,
    paddingBottom: 14,
    gap: 0,
  },
  bottomProgressDhikrSolo: {
    marginTop: 0,
  },
  scrollContentFull: {
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  centeredStep: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    paddingTop: 20,
    paddingHorizontal: 4,
  },
  fullScreen: {
    width: SCREEN_W,
    height: SCREEN_H,
    position: "relative",
  },
  fullImage: {
    width: "100%",
    height: "100%",
  },
  imageOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "60%",
  },
  imageSlideArtWrap: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  /** Onboarding image slides 0â€“1 only: top intro zone (not title/body hierarchy) */
  imageSlideIntroWrap: {
    position: "absolute",
    left: 24,
    right: 24,
    alignItems: "flex-start",
  },
  smallTag: {
    fontSize: 13,
    color: "rgba(196,162,247,0.7)",
    fontFamily: "Inter_400Regular",
    letterSpacing: 0.5,
  },
  imageSlideIntroText: {
    fontSize: 31,
    fontFamily: "Inter_500Medium",
    color: "#f4eeff",
    lineHeight: 39,
    letterSpacing: -0.05,
    width: "100%",
    textAlign: "left",
  },
  imageStepArrowFab: {
    position: "absolute",
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#C4A2F7",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 8,
  },
  mascotMedium: {
    width: 140,
    height: 140,
  },
  mascotStage: {
    width: 178,
    height: 178,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  artStage: {
    width: 250,
    height: 250,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  artFloatLayer: {
    alignItems: "center",
    justifyContent: "center",
  },
  artGlow: {
    position: "absolute",
    width: 214,
    height: 214,
    borderRadius: 107,
    backgroundColor: "rgba(196,162,247,0.2)",
    shadowColor: "#F3D792",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 34,
    elevation: 0,
  },
  mascotGlow: {
    position: "absolute",
    width: 152,
    height: 152,
    borderRadius: 76,
    backgroundColor: "rgba(196,162,247,0.18)",
    shadowColor: "#F3D792",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 0,
  },
  artSurface: {
    width: 236,
    height: 236,
    borderRadius: 118,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(32,14,54,0.18)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 22,
    elevation: 0,
  },
  mascotSurface: {
    width: 168,
    height: 168,
    borderRadius: 84,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(32,14,54,0.18)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 22,
    elevation: 0,
  },
  artMascot: {
    width: "100%",
    height: "100%",
  },
  heroMascotLarge: {
    width: "116%",
    height: "116%",
  },
  heroMascotMedium: {
    width: "114%",
    height: "114%",
  },
  framedMascotLarge: {
    width: "108%",
    height: "108%",
  },
  framedMascotMedium: {
    width: "110%",
    height: "110%",
  },
  mascotLarge: {
    width: 240,
    height: 240,
  },
  stepTitle: {
    fontSize: 28,
    fontFamily: "Inter_700Bold",
    color: "#f0eaff",
    textAlign: "center",
    lineHeight: 38,
    letterSpacing: 0.12,
    marginTop: 4,
    maxWidth: 300,
  },
  /** Age step: validation line (no subtitle row above — override goals hint’s negative top). */
  ageRangeValidationHint: {
    marginTop: 16,
    marginBottom: 4,
  },
  /** Age step: wraps option stack for horizontal shake; `marginTop` tuned in component when hint is visible. */
  ageRangeShakeBlock: {
    width: "100%",
    alignItems: "center",
    paddingTop: 28,
  },
  ageRangeStack: {
    width: "100%",
    maxWidth: 228,
    alignSelf: "center",
    gap: 10,
  },
  ageRangeOptionGradient: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  ageRangeOptionLabel: {
    fontSize: 17,
    lineHeight: 24,
    fontFamily: "Inter_500Medium",
    letterSpacing: 0.06,
    textAlign: "center",
    width: "100%",
  },
  stepSub: {
    fontSize: 15,
    color: "rgba(196,162,247,0.75)",
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 23,
    paddingHorizontal: 4,
    maxWidth: 310,
  },
  /** Check-in transition step (12): calm hero + minimal meta; full-width centering inside scroll. */
  checkinTransitionRoot: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
  },
  checkinTransitionMeta: {
    marginTop: 8,
    alignItems: "center",
    gap: 14,
  },
  checkinTransitionReassurance: {
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    color: "rgba(244, 238, 255, 0.52)",
    textAlign: "center",
    letterSpacing: 0.15,
    lineHeight: 22,
    paddingHorizontal: 32,
  },
  phoneHoursScreen: {
    flex: 1,
    width: "100%",
    alignSelf: "stretch",
    paddingHorizontal: 4,
    paddingTop: 50,
  },
  /** Full headline typography + layout (same merged result as former stepTitle + phoneHoursHeading). */
  phoneHoursHeading: {
    fontSize: 28,
    fontFamily: "Inter_700Bold",
    color: "#f0eaff",
    textAlign: "center",
    lineHeight: 38,
    letterSpacing: 0.12,
    marginTop: 0,
    marginBottom: 8,
    maxWidth: 340,
    alignSelf: "center",
    width: "100%",
  },
  /** Dhikr frequency: title wraps naturally with “per week?” on mobile. */
  phoneHoursHeadingFrequency: {
    maxWidth: "92%",
    lineHeight: 38,
    marginBottom: 20,
  },
  /** Stretch like phoneHoursScreen column so line wraps / block height match the reference step. */
  phoneHoursTextBlock: {
    width: "100%",
    maxWidth: 340,
    alignSelf: "center",
    alignItems: "stretch",
  },
  /** Tighten gap between headline and subtitle when both are used (mood baseline step). */
  phoneHoursHeadingAboveSub: {
    marginBottom: 4,
  },
  /** Space from subtitle block to the flex middle zone (matches single-line headline marginBottom). */
  phoneHoursSubAboveMiddle: {
    marginBottom: 8,
  },
  /** Mood tier label in the same slot as phone-hours big number (hero readout above slider). */
  phoneHoursMoodLabel: {
    fontSize: 40,
    fontFamily: "Inter_700Bold",
    color: "#f0eaff",
    lineHeight: 44,
    letterSpacing: -1,
    textAlign: "center",
    maxWidth: 320,
  },
  /** Dhikr frequency: caption under hero number (explains the level, not a title). */
  phoneHoursMoodLabelFrequency: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 19,
    letterSpacing: 0.2,
    maxWidth: "92%",
    color: "rgba(240,234,255,0.48)",
  },
  /** Subtle reassurance beneath the frequency slider. */
  phoneHoursFrequencyReassurance: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: "rgba(240,234,255,0.38)",
    textAlign: "center",
    lineHeight: 17,
    maxWidth: "90%",
    paddingHorizontal: 6,
  },
  /** Slider + hint grouped so phoneHoursStep gap matches the reference step. */
  phoneHoursSliderStack: {
    width: "100%",
    alignItems: "center",
    gap: 12,
  },
  /** Dhikr frequency: space under the slider before reassurance line. */
  phoneHoursSliderStackFrequency: {
    gap: 16,
    marginTop: 0,
    paddingBottom: 6,
  },
  /** Full supporting typography + layout (same merged result as former stepSub + phoneHoursSub). */
  phoneHoursSub: {
    fontSize: 15,
    color: "rgba(196,162,247,0.75)",
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 23,
    paddingHorizontal: 4,
    maxWidth: 340,
    width: "100%",
    alignSelf: "center",
    marginTop: 0,
  },
  phoneHoursMiddle: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    minHeight: 0,
  },
  /** Lets the step column use full middle height (dhikr frequency layout). */
  phoneHoursMiddleExpanded: {
    alignItems: "stretch",
  },
  phoneHoursStepExpanded: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    maxWidth: 340,
    alignSelf: "center",
  },
  phoneHoursStep: {
    width: "100%",
    maxWidth: 340,
    alignItems: "center",
    gap: 32,
  },
  /** Dhikr frequency: column fills middle; hero + lower controls. */
  phoneHoursFrequencyStep: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    alignItems: "center",
  },
  /** Vertical space for the large level number (centered in remaining area above controls). */
  phoneHoursFrequencyHeroZone: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    minHeight: 112,
    paddingVertical: 12,
    overflow: "visible",
  },
  /** Caption, slider, reassurance — visually below the hero number with air. */
  phoneHoursFrequencyLower: {
    width: "100%",
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 10,
    gap: 20,
  },
  /** Large level readout (plain fill; no glow / text shadow). */
  phoneHoursFrequencyHeroNum: {
    fontSize: 96,
    fontFamily: "Inter_600SemiBold",
    color: "#EDE8FA",
    lineHeight: 102,
    letterSpacing: -4,
    textAlign: "center",
  },
  phoneHoursValueBlock: {
    alignItems: "center",
    gap: 4,
    transform: [{ translateY: -40 }],
  },
  phoneHoursBigNum: {
    fontSize: 72,
    fontFamily: "Inter_700Bold",
    color: "#f0eaff",
    lineHeight: 76,
    letterSpacing: -2,
  },
  phoneHoursUnit: {
    fontSize: 17,
    fontFamily: "Inter_500Medium",
    color: "#f0eaff",
  },
  screenTimeReflect: {
    flex: 1,
    width: "100%",
    maxWidth: 340,
    alignSelf: "flex-start",
    paddingHorizontal: 4,
    paddingTop: 32,
    paddingBottom: 12,
  },
  screenTimeReflectBlock: {
    marginBottom: 30,
  },
  screenTimeReflectParagraph: {
    fontSize: 22,
    fontFamily: "Inter_500Medium",
    lineHeight: 32,
    textAlign: "left",
    width: "100%",
  },
  screenTimeReflectBody: {
    fontSize: 22,
    fontFamily: "Inter_500Medium",
    lineHeight: 32,
  },
  screenTimeReflectAccent: {
    fontSize: 22,
    fontFamily: "Inter_700Bold",
    lineHeight: 32,
    letterSpacing: 0.2,
  },
  pillRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  featurePill: {
    backgroundColor: "rgba(196,162,247,0.12)",
    borderColor: "rgba(196,162,247,0.25)",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  pillText: {
    color: "#C4A2F7",
    fontSize: 13,
    fontFamily: "Inter_500Medium",
  },
  appGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
    maxWidth: 340,
  },
  appCard: {
    width: "46%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(45,26,74,0.6)",
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  appCardSelected: {
    backgroundColor: "rgba(196,162,247,0.1)",
  },
  appLabel: {
    fontSize: 14,
    fontFamily: "Inter_500Medium",
  },
  nameEntryWrap: {
    width: "100%",
    maxWidth: 340,
    alignItems: "center",
    gap: 16,
    transform: [{ translateY: -28 }],
  },
  journeyHeroCard: {
    width: "100%",
    height: 320,
    borderRadius: 36,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(223,204,255,0.08)",
    backgroundColor: "rgba(34,23,55,0.84)",
    marginTop: 12,
    marginBottom: 12,
    shadowColor: "#0B0717",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 22,
    elevation: 0,
  },
  journeyHeroGradient: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
  },
  journeyBoardLayer: {
    ...StyleSheet.absoluteFillObject,
    paddingHorizontal: JOURNEY_GRID_SIDE_PADDING,
    paddingVertical: JOURNEY_GRID_VERTICAL_PADDING,
    justifyContent: "center",
    alignItems: "center",
  },
  journeyBoardGrid: {
    alignSelf: "center",
    justifyContent: "flex-start",
  },
  journeyBoardRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  journeyDayCell: {
    borderWidth: 1,
    borderColor: "rgba(214,193,245,0.08)",
    backgroundColor: "rgba(179,152,221,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  journeyDayCellFuture: {
    borderColor: "rgba(214,193,245,0.1)",
    backgroundColor: "rgba(172,142,218,0.05)",
  },
  journeyDayCellCompleted: {
    borderColor: "rgba(0,0,0,0)",
    backgroundColor: "rgba(186,158,232,0.18)",
    shadowColor: "#C9B2EB",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.11,
    shadowRadius: 5,
    elevation: 0,
  },
  journeyDayCellRecent: {
    borderColor: "rgba(0,0,0,0)",
    backgroundColor: "rgba(203,174,244,0.24)",
    shadowColor: "#C8ACEB",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 7,
    elevation: 0,
  },
  journeyDayCellToday: {
    borderColor: "rgba(250,218,165,0.42)",
    backgroundColor: "rgba(242,198,120,0.34)",
    shadowColor: "#F5C26D",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 9,
    elevation: 0,
  },
  journeyDayMark: {
    color: "rgba(244,237,255,0.72)",
  },
  journeyDayMarkRecent: {
    color: "rgba(248,240,255,0.82)",
  },
  journeyDayMarkToday: {
    color: "rgba(255,238,204,0.96)",
  },
  journeyBoardVeil: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(14,9,25,0.06)",
  },
  journeyCardEdge: {
    ...StyleSheet.absoluteFillObject,
  },
  nameEntryTitle: {
    color: "#f0eaff",
    fontSize: 30,
    fontFamily: "Inter_500Medium",
    textAlign: "center",
    lineHeight: 35,
    maxWidth: 320,
    marginTop: 2,
    transform: [{ translateY: -20 }],
  },
  nameEntrySubtitle: {
    fontSize: 14,
    color: "rgba(216,199,245,0.68)",
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    marginTop: -2,
    marginBottom: 2,
  },
  nameEntryInput: {
    width: "100%",
    backgroundColor: "rgba(45,26,74,0.5)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(196,162,247,0.18)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#f0eaff",
    fontSize: 16,
    fontFamily: "Inter_400Regular",
    marginTop: 8,
  },
  ritualSub: {
    color: "#9b80c8",
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  goalList: {
    gap: 10,
    width: "100%",
  },
  /** List + chrome rail in a row: rail sits outside the card stack with a fixed gap. */
  goalsListScrollRow: {
    flexDirection: "row",
    alignItems: "stretch",
    width: "100%",
    marginTop: 32,
    gap: 8,
  },
  goalsListScrollListCol: {
    flex: 1,
    minWidth: 0,
    position: "relative",
  },
  goalsListScrollViewport: {
    width: "100%",
  },
  /** Subtle cue that more goals exist below; scoped to list column only. */
  goalsScrollBottomFade: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 44,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  /** Chrome column: same height as ScrollView via row stretch, no overlap with cards. */
  goalsScrollRail: {
    width: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  goalsScrollTrack: {
    flex: 1,
    width: 3,
    maxWidth: 3,
    marginVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(196,162,247,0.08)",
    overflow: "hidden",
  },
  goalsScrollThumb: {
    position: "absolute",
    left: 0,
    width: 3,
    borderRadius: 999,
    backgroundColor: "rgba(196,162,247,0.2)",
  },
  goalsListScrollContent: {
    gap: GOALS_LIST_ROW_GAP,
    paddingBottom: 20,
  },
  goalsListRowMeasureWrap: {
    width: "100%",
  },
  /** Goals step (screen 7): top-weighted, intrinsic height (no flex:1) so ScrollView can scroll past the footer. */
  goalsReflectStep: {
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 0,
    paddingTop: 8,
    paddingHorizontal: 4,
    /** +12 vs 340: room for 8px gap + 3px rail outside list without narrowing cards. */
    maxWidth: 352,
    width: "100%",
    alignSelf: "center",
  },
  goalsReflectTitleBlock: {
    width: "100%",
    alignItems: "center",
    paddingTop: 10,
  },
  /** Mascot left of subtitle, vertically centered; whole row centered as a unit. */
  goalsReflectSubRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 18,
    marginBottom: 18,
    gap: 10,
  },
  /** Struggle step: same vertical rhythm as goalsReflectSubRow, subtitle only (no mascot offset). */
  goalsReflectSubBlockCentered: {
    width: "100%",
    alignItems: "center",
    marginTop: 18,
    marginBottom: 18,
  },
  goalsStepTitle: {
    fontSize: 29,
    fontFamily: "Inter_700Bold",
    color: "#f0eaff",
    textAlign: "center",
    lineHeight: 42,
    letterSpacing: 0.08,
    maxWidth: 278,
    textShadowColor: "rgba(196,162,247,0.14)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
  },
  /** Barriers step: use full card width + slightly smaller type so three `\n` lines stay one row each on phones. */
  goalsStepTitleBarriers: {
    maxWidth: "100%",
    width: "100%",
    fontSize: 26,
    lineHeight: 33,
    letterSpacing: 0.05,
  },
  goalsStepSub: {
    fontSize: 15,
    color: "rgba(196,162,247,0.5)",
    fontFamily: "Inter_400Regular",
    textAlign: "left",
    lineHeight: 23,
    paddingHorizontal: 0,
    maxWidth: 248,
    flexShrink: 1,
  },
  goalsPickValidationHint: {
    width: "100%",
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "rgba(196,162,247,0.72)",
    textAlign: "center",
    marginTop: -10,
    marginBottom: 8,
    paddingHorizontal: 12,
  },
  /** Strong-relationship step: subtitle block is tighter; avoid overlap with â€œChoose all that resonate.â€ */
  goalsRelationshipPickValidationHint: {
    marginTop: 10,
  },
  /** Same sizing/tone as goalsStepSub, centered for mascot-free struggle step. */
  goalsStepSubCentered: {
    fontSize: 15,
    color: "rgba(196,162,247,0.5)",
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 23,
    paddingHorizontal: 4,
    maxWidth: 310,
  },
  /** Matches OnboardingMascot: circular surface + glow; compact for header accent. */
  goalsMascotStage: {
    width: 58,
    height: 58,
    alignItems: "center",
    justifyContent: "center",
  },
  goalsMascotGlow: {
    position: "absolute",
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(196,162,247,0.18)",
    shadowColor: "#F3D792",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 0,
    top: 5,
    left: 5,
  },
  goalsMascotSurface: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(32,14,54,0.18)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 0,
  },
  goalsMascotImg: {
    width: "110%",
    height: "110%",
  },
  goalsPickPressable: {
    width: "100%",
    borderRadius: 14,
  },
  goalsPickPressableSelected: {
    shadowColor: "#C4A2F7",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 3,
  },
  goalsPickOuter: {
    borderRadius: 14,
    overflow: "hidden",
  },
  goalsPickGradient: {
    paddingVertical: 15,
    paddingHorizontal: 16,
  },
  goalsPickGradientCompact: {
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  goalsPickRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  goalsPickRowTopAlign: {
    alignItems: "flex-start",
  },
  goalsCheckRingTopAlign: {
    marginTop: 2,
  },
  goalsPickLabelCol: {
    flex: 1,
    minWidth: 0,
  },
  goalsCheckRing: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "rgba(196,162,247,0.38)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  goalsCheckFill: {
    position: "absolute",
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  goalsCheckMarkWrap: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  goalItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(45,26,74,0.5)",
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 15,
    paddingHorizontal: 16,
  },
  goalItemSelected: {
    backgroundColor: "rgba(196,162,247,0.08)",
  },
  goalCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "rgba(196,162,247,0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  goalLabel: {
    fontSize: 15,
    fontFamily: "Inter_500Medium",
    flex: 1,
  },
  /** Multi-line onboarding options: tighter line rhythm, slightly smaller type. */
  goalLabelCompact: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.05,
  },
  goalsRelationshipTitle: {
    maxWidth: 322,
    lineHeight: 34,
    fontSize: 28,
  },
  goalsReflectSubRelationship: {
    marginTop: 12,
    marginBottom: 2,
    paddingTop: 10,
  },
  goalsRelationshipSub: {
    lineHeight: 21,
    fontSize: 14,
  },
  goalsRelationshipListScrollRow: {
    marginTop: 44,
  },
  goalsRelationshipListScrollContent: {
    gap: 7,
    paddingBottom: 14,
  },
  sliderBlock: {
    alignItems: "center",
    gap: 16,
    paddingTop: 20,
  },
  sliderLabel: {
    fontSize: 22,
    fontFamily: "Inter_600SemiBold",
    color: "#f0eaff",
  },
  sliderHint: {
    fontSize: 13,
    color: "rgba(155,128,200,0.7)",
    fontFamily: "Inter_400Regular",
  },
  previewCards: {
    flexDirection: "row",
    gap: 10,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  previewCard: {
    width: 100,
    backgroundColor: "rgba(45,26,74,0.7)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(196,162,247,0.15)",
    paddingVertical: 18,
    paddingHorizontal: 10,
    alignItems: "center",
    gap: 8,
  },
  previewIcon: {
    fontSize: 22,
  },
  previewCardTitle: {
    color: "#f0eaff",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
  },
  previewCardSub: {
    color: "#9b80c8",
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
  },
  verseCard: {
    backgroundColor: "rgba(45,26,74,0.7)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(245,200,66,0.2)",
    padding: 24,
    width: "100%",
    alignItems: "center",
    gap: 10,
  },
  verseArabic: {
    fontSize: 26,
    color: "#F5C842",
    fontFamily: "Inter_700Bold",
    textAlign: "center",
    lineHeight: 40,
  },
  verseTranslit: {
    color: "rgba(240,234,255,0.8)",
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    fontStyle: "italic",
    textAlign: "center",
  },
  verseTranslation: {
    color: "#f0eaff",
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 20,
  },
  verseRef: {
    color: "#9b80c8",
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  streakPreview: {
    flexDirection: "row",
    gap: ONBOARDING_STREAK_DAY_ROW_GAP,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    maxWidth: "100%",
  },
  streakDay: {
    width: ONBOARDING_STREAK_DAY_CELL_SIZE,
    height: ONBOARDING_STREAK_DAY_CELL_SIZE,
    borderRadius: ONBOARDING_STREAK_DAY_CELL_SIZE / 2,
    backgroundColor: "rgba(45,26,74,0.6)",
    borderWidth: 1,
    borderColor: "rgba(196,162,247,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  streakDayInactive: {
    opacity: 0.38,
  },
  streakDayActive: {
    backgroundColor: "#C4A2F7",
    borderColor: "rgba(245,200,66,0.45)",
  },
  streakDay1Wrap: {
    shadowColor: "#C4A2F7",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 18,
    elevation: 10,
  },
  streakRewardStack: {
    position: "relative",
    width: "100%",
    alignItems: "center",
    gap: 68,
    paddingTop: 32,
    paddingBottom: 16,
  },
  streakIconWrap: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    width: 88,
    height: 72,
  },
  streakSparkle: {
    position: "absolute",
    color: "rgba(245,200,66,0.55)",
    fontSize: 11,
    fontFamily: "Inter_500Medium",
  },
  streakDayLabel: {
    fontSize: 17,
    fontFamily: "Inter_600SemiBold",
  },
  streakDay1Inner: {
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  streakDayFire: {
    fontSize: 13,
    lineHeight: 16,
    marginBottom: -2,
  },
  notifList: {
    gap: 12,
    width: "100%",
  },
  notifItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: "rgba(45,26,74,0.5)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(196,162,247,0.12)",
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  notifLabel: {
    color: "#f0eaff",
    fontSize: 15,
    fontFamily: "Inter_500Medium",
  },
  protectionStep: {
    justifyContent: "center",
    gap: 28,
    width: "100%",
    maxWidth: 332,
    alignSelf: "center",
    paddingHorizontal: 8,
    paddingTop: 0,
    paddingBottom: 8,
    transform: [{ translateY: -26 }],
  },
  protectionIconStage: {
    width: 128,
    height: 128,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  protectionIconGlow: {
    position: "absolute",
    width: 114,
    height: 114,
    borderRadius: 57,
    backgroundColor: "rgba(196,162,247,0.12)",
    shadowColor: "#C4A2F7",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 0,
  },
  protectionIconSurface: {
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(25,13,41,0.42)",
    alignItems: "center",
    justifyContent: "center",
  },
  protectionTitle: {
    fontSize: 32,
    fontFamily: "Inter_700Bold",
    color: "#F0EAFF",
    textAlign: "center",
    lineHeight: 40,
    letterSpacing: 0.08,
    maxWidth: 320,
  },
  protectionExplanationCard: {
    width: "100%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(196,162,247,0.2)",
    backgroundColor: "rgba(33,19,55,0.5)",
    paddingHorizontal: 18,
    paddingVertical: 17,
    gap: 14,
  },
  protectionBody: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    color: "rgba(240,234,255,0.92)",
    fontFamily: "Inter_400Regular",
  },
  protectionControlNote: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
    color: "rgba(210,192,244,0.76)",
    fontFamily: "Inter_500Medium",
  },
  protectionPermissionHint: {
    fontSize: 12,
    lineHeight: 17,
    textAlign: "center",
    color: "rgba(196,162,247,0.66)",
    fontFamily: "Inter_400Regular",
    marginTop: -4,
    maxWidth: 300,
  },
  /** Paywall: single column inside CenteredStep for controlled vertical rhythm. */
  paywallCenteredStep: {
    gap: 0,
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 6,
    justifyContent: "center",
  },
  paywallRoot: {
    width: "100%",
    maxWidth: 336,
    alignSelf: "center",
    alignItems: "stretch",
  },
  paywallHeroSection: {
    width: "100%",
    alignItems: "stretch",
    marginBottom: 16,
  },
  /** Centered hero art column; spacing below before “Choose your plan”. */
  heroArtContainer: {
    width: "100%",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 22,
    overflow: "visible",
  },
  /** Soft purple ambient behind paywall art — no gold frame or harsh glow. */
  paywallArtAmbient: {
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    backgroundColor: "rgba(22, 10, 42, 0.26)",
    borderRadius: 18,
    shadowColor: "#1a0a2e",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 26,
    elevation: 4,
  },
  heroArtImage: {
    backgroundColor: "transparent",
    borderRadius: 24,
    overflow: "hidden",
  },
  paywallHeadlineBlock: {
    width: "100%",
    alignItems: "center",
    marginTop: 0,
    marginBottom: 0,
  },
  paywallTitle: {
    fontSize: 27,
    fontFamily: "Inter_700Bold",
    color: "#f0eaff",
    textAlign: "center",
    lineHeight: 34,
    letterSpacing: 0.1,
    marginBottom: 6,
    maxWidth: 320,
  },
  paywallSubtitle: {
    fontSize: 15,
    color: "rgba(220,204,250,0.82)",
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 23,
    paddingHorizontal: 8,
    maxWidth: 318,
  },
  paywallCardsStack: {
    width: "100%",
    marginBottom: 20,
  },
  /** Vertical gap between yearly and weekly plan cards. */
  planCardSpacing: {
    gap: 18,
  },
  paywallCardPressable: {
    width: "100%",
    borderRadius: 20,
  },
  paywallCardInner: {
    width: "100%",
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 16,
    position: "relative",
    gap: 2,
  },
  paywallCardYearly: {
    backgroundColor: "rgba(36,22,58,0.72)",
    borderWidth: 1.5,
    borderColor: "rgba(245,200,66,0.65)",
    shadowColor: "#F5C842",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
  },
  paywallCardYearlyUnselected: {
    borderColor: "rgba(245,200,66,0.35)",
    shadowOpacity: 0.06,
  },
  paywallCardWeekly: {
    backgroundColor: "rgba(32,18,52,0.45)",
    borderWidth: 1,
    borderColor: "rgba(196,162,247,0.14)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 1,
  },
  paywallCardWeeklySelected: {
    borderColor: "rgba(196,162,247,0.38)",
    backgroundColor: "rgba(45,26,74,0.55)",
  },
  paywallTrialBadge: {
    position: "absolute",
    top: 10,
    right: 12,
    zIndex: 2,
    backgroundColor: "#F5C842",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    maxWidth: "52%",
  },
  paywallTrialBadgeText: {
    color: "#1a0a2e",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.2,
    textAlign: "center",
  },
  paywallCardRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    paddingRight: 4,
  },
  paywallSelectRing: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(196,162,247,0.45)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    backgroundColor: "transparent",
  },
  paywallSelectRingActive: {
    borderColor: "#F5C842",
    backgroundColor: "rgba(245,200,66,0.2)",
  },
  paywallSelectRingWeeklyActive: {
    borderColor: "rgba(196,162,247,0.65)",
    backgroundColor: "rgba(196,162,247,0.15)",
  },
  paywallCardTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 4,
    paddingTop: 0,
  },
  paywallCardTextColYearly: {
    paddingRight: 92,
  },
  paywallPlanYearly: {
    color: "#f0eaff",
    fontSize: 17,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.15,
  },
  paywallPlanWeekly: {
    color: "rgba(240,234,255,0.78)",
    fontSize: 16,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.12,
  },
  paywallPriceYearly: {
    color: "#EDE8FA",
    fontSize: 17,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.08,
  },
  paywallPriceWeekly: {
    color: "rgba(196,162,247,0.72)",
    fontSize: 16,
    fontFamily: "Inter_600SemiBold",
  },
  paywallSubYearly: {
    color: "rgba(180,158,220,0.88)",
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    lineHeight: 17,
  },
  paywallRestoreRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
    marginTop: 40,
    marginBottom: 2,
  },
  paywallRestoreWrap: {
    paddingVertical: 0,
  },
  paywallPrimaryButtonInner: {
    paddingVertical: 21,
  },
  paywallFooter: {
    paddingTop: 8,
    paddingBottom: 16,
    gap: 8,
  },
  paywallCtaElevated: {
    shadowColor: "#E8B84B",
    shadowOpacity: 0.42,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  /** Extra scroll inset so paywall content clears the fixed footer on small phones. */
  scrollContentPaywallStep: {
    paddingBottom: 112,
  },
  restoreText: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    textDecorationLine: "underline",
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 12,
    gap: 4,
  },
  bottomProgress: {
    marginTop: 8,
    alignItems: "center",
  },
  imageBottomProgress: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
  },
  appLockContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    // Move the grid+headline block down to avoid a top-heavy feel.
    paddingTop: 0,
    paddingHorizontal: 22,
    paddingBottom: 40,
  },
  contentWrapper: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    /** Match `goalsReflectStep.paddingTop` so app-lock headline aligns with age step title. */
    paddingTop: 8,
  },
  contentStack: {
    alignItems: "center",
    gap: 38,
  },
  /** App lock: center icon grid + subtitle in space below the pinned headline (original vertical rhythm). */
  appLockIconsSubtitleCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    minHeight: 0,
  },
  appLockIconsSubtitleStack: {
    alignItems: "center",
    gap: 38,
  },
  appLockIconGrid: {
    flexDirection: "column",
    gap: 74,
    alignItems: "center",
  },
  appLockIconRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 74,
  },
  appLockCard: {
    width: 82,
    height: 82,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "visible",
  },
  appLockCardScaledShell: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: 23,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    transform: [{ scale: 1.3 }],
  },
  appLockIconLayer: {
    zIndex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  appLockCardGlow: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: "rgba(196,162,247,0.1)",
    shadowColor: "#C4A2F7",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 0,
  },
  appLockIconClip: {
    width: 64,
    height: 64,
    borderRadius: 18,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  appLockIconImage: {
    opacity: 1,
  },
  appLockLockBadge: {
    position: "absolute",
    zIndex: 2,
    top: 4,
    right: 4,
    alignItems: "center",
    justifyContent: "center",
    padding: 2,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.4)",
    transformOrigin: "right top",
    transform: [{ scale: 1.35 }],
  },
  appLockCopyWrap: {
    alignItems: "center",
    width: 196,
    paddingHorizontal: 0,
    gap: 0,
  },
  appLockHeadline: {
    fontSize: 21,
    fontFamily: "Inter_500Medium",
    color: "#f0eaff",
    textAlign: "center",
    lineHeight: 27,
    letterSpacing: -0.08,
    maxWidth: 304,
  },
  appLockSubline: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "rgba(196,162,247,0.62)",
    textAlign: "center",
    lineHeight: 19,
  },
  appLockArrowPress: {
    marginBottom: 0,
  },
  appLockArrowInner: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  appLockBottom: {
    width: "100%",
    alignItems: "center",
    gap: 22,
    paddingBottom: 0,
  },
  appLockProgressWrap: {
    width: "100%",
    alignItems: "center",
    marginTop: 0,
  },
  appLockProgressTrack: {
    width: "78%",
    height: 2,
    borderRadius: 999,
    backgroundColor: "rgba(196,162,247,0.12)",
    overflow: "hidden",
  },
  appLockProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "rgba(235,226,255,0.46)",
  },
  nextBtn: {
    width: "100%",
  },
});
